name = "CherryMoonlight"
author = "OoLunar"
version = "1.25.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8e6d7b068b2764ea5b74d6abd00bcfcab2deaf6c2778cafde3adb345eb4a31f9"

[versions]
forge = "43.3.9"
minecraft = "1.19.2"

[options]
datapack-folder = "datapacks"
