name = "CherryMoonlight"
author = "OoLunar"
version = "1.24.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7afdde070e32e909a6386417b41097f2d0e86c91e4559056f96d79b1ab1625da"

[versions]
forge = "43.3.9"
minecraft = "1.19.2"

[options]
datapack-folder = "datapacks"
