name = "CherryMoonlight"
author = "OoLunar"
version = "1.24.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b24e47a02ae383a4cc2d8c5935f162cac70de092dd17746d53410b71ddab8e01"

[versions]
forge = "43.3.9"
minecraft = "1.19.2"

[options]
datapack-folder = "datapacks"
