name = "CherryMoonlight"
author = "OoLunar"
version = "1.24.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1a7ab44737bc4d69d378fbd9be00faff89aeb8677295870180ccca456b740056"

[versions]
forge = "43.3.9"
minecraft = "1.19.2"

[options]
datapack-folder = "datapacks"
