name = "CherryMoonlight"
author = "OoLunar"
version = "1.24.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "db0848054aafdae97bd9903f120c15b04ec0b61132884f084438240a0364e3cb"

[versions]
forge = "43.3.9"
minecraft = "1.19.2"

[options]
datapack-folder = "datapacks"
