name = "CherryMoonlight"
author = "OoLunar"
version = "1.26.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "13806f3d79ed9840cc52f9ce1789b520e7198a38127383411e5026d9d1ded1cd"

[versions]
forge = "43.3.9"
minecraft = "1.19.2"

[options]
datapack-folder = "datapacks"
