name = "CherryMoonlight"
author = "OoLunar"
version = "1.25.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c583edc80453a45f94b9f5e1b0c6823e1968e885821316cb1bc920d69e8a4fa7"

[versions]
forge = "43.3.9"
minecraft = "1.19.2"

[options]
datapack-folder = "datapacks"
